/**
 * The model, as PlantUML.
 *
 * An **export and never an input**, which `model.ts` says at length and this
 * file has to keep true. A round trip through a rendering language would lose
 * the invariants, the by-identity rule and the difference between a value
 * object and an entity — everything the format exists to carry — and would hand
 * us the second source of truth the component refuses. So the emitted file says
 * so in its first two lines, for the benefit of whoever finds it in a wiki and
 * reaches for it to make a change.
 *
 * What survives the translation, and how:
 *
 *   an aggregate      a `package <<Aggregate>>`, because its members nesting
 *                     inside it is the boundary and not a folder
 *   an invariant      a note on the root, so the rationale travels with the
 *                     picture rather than being the thing that gets dropped
 *   identity          the root's `id` row, which is the definition of an entity
 *                     and not a style preference
 *   `contains`        composition, a filled diamond: the part has no life of
 *                     its own
 *   `embeds`          shared aggregation, a hollow one — the same two diamonds
 *                     the canvas draws
 *   `references`      a dashed dependency, which is exactly what holding an id
 *                     across a boundary looks like
 *
 * The multiplicity words become `1`, `0..1`, `*` and `1..*` here: the audience
 * for a rendered diagram reads UML, and `multiplicityMark` in `model.ts` is
 * where that translation lives.
 *
 * ## It looks like the editor
 *
 * The stereotypes, the rows and the palette are the canvas's, taken from the
 * same functions the canvas draws with — `rowsOf` and `stereotypeOf` from
 * `layout.ts` — so a rendered `.puml` and a screenshot of the tool are the same
 * picture rather than two pictures of the same model. Only the arrangement
 * differs, because PlantUML lays the boxes out itself and that is the one thing
 * it is better at than we are.
 *
 * The palette is the canvas's **light** theme, in hex. The graph's colours are
 * Tailwind classes, which resolve against a stylesheet PlantUML has never heard
 * of, so they are written out here — the same problem the SVG export solves by
 * baking computed styles in, and the same answer. Light rather than the pinned
 * theme, because a `.puml` gets rendered by somebody else's server into
 * somebody else's page.
 */

import {
	multiplicityMark,
	type AggregateNode,
	type DomainModel,
	type Id,
	type Member,
} from './model';
import { rowsOf, stereotypeOf } from './layout';

/**
 * The canvas's light palette, written out.
 *
 * Every entry is the Tailwind colour the corresponding element carries in
 * `Diagram.tsx`, named after the role rather than the swatch so that the two
 * can be compared line by line when one of them moves.
 */
const PALETTE = {
	/** `--color-ink` and `--color-ink-muted` from global.css. */
	ink: '#211c2b',
	inkMuted: '#6b6578',
	/** The aggregate box: violet-50 with a dashed violet-400 border. */
	aggregateFill: '#f5f3ff',
	aggregateBorder: '#a78bfa',
	aggregateTitle: '#4c1d95',
	/** The root: violet, for the same reason a core subdomain is violet. */
	rootFill: '#ede9fe',
	rootBorder: '#8b5cf6',
	rootTitle: '#2e1065',
	/** An entity: sky. */
	entityFill: '#f0f9ff',
	entityBorder: '#38bdf8',
	/** An enumeration and a value object: grey, and white. */
	enumFill: '#f8fafc',
	valueFill: '#ffffff',
	greyBorder: '#94a3b8',
	/** Links, and the note the invariants live in. */
	line: '#64748b',
	noteFill: '#faf5ff',
	noteBorder: '#c4b5fd',
	page: '#ffffff',
} as const;

export function toPuml(model: DomainModel): string {
	const alias = aliases(model);
	const lines: string[] = [];

	lines.push(
		`' The inside of "${model.context}", generated by ba-ddd-mapper.`,
		"' The .ddm file is the source of truth. This is an export: edit that, not this.",
		'',
		`@startuml ${quoted(model.context)}`,
		...skin(),
		'',
	);

	for (const aggregate of model.aggregates) {
		lines.push(
			`package ${quoted(aggregate.name)} <<aggregate>> ${PALETTE.aggregateFill} {`,
			...membersOf(model, aggregate).flatMap((member) => declare(member, alias, '\t')),
			'}',
			'',
		);
	}

	// Values and enumerations shared across the aggregates: outside every
	// boundary, which is the whole reason the format lets them be declared there.
	const loose = model.members.filter((member) => member.aggregate === null);
	if (loose.length > 0) {
		lines.push(...loose.flatMap((member) => declare(member, alias, '')), '');
	}

	for (const aggregate of model.aggregates) {
		const note = noteFor(aggregate, alias);
		if (note.length > 0) lines.push(...note, '');
	}

	for (const link of model.links) {
		const from = alias.get(link.from);
		const to = alias.get(link.to);
		// A link whose ends did not survive the parse is dropped rather than
		// emitted half-written: the problems panel already says so, and a broken
		// arrow in a rendered picture says it much less clearly.
		if (!from || !to) continue;
		// `references` always names an aggregate and lands on its root, so it says
		// so: on the canvas the arrow ends on the aggregate's box, and here the
		// nearest true thing is the class that box is the face of.
		const label = link.kind === 'references' ? ' : references' : '';
		lines.push(
			`${from} ${arrowFor(link.kind)} "${multiplicityMark[link.multiplicity]}" ${to}${label}`,
		);
	}

	lines.push('', '@enduml', '');
	return lines.join('\n');
}

/** The two diamonds and the dashed arrow, as the canvas draws them. */
function arrowFor(kind: 'contains' | 'embeds' | 'references'): string {
	if (kind === 'contains') return '*--';
	if (kind === 'embeds') return 'o--';
	return '..>';
}

/**
 * The skin, which is the canvas's stylesheet said in PlantUML's language.
 *
 * Per-class colours are written inline on each declaration rather than through
 * `skinparam ...<<stereotype>>`, because inline colours are honoured by every
 * renderer that understands them and ignored quietly by the rest, which is the
 * better failure: a diagram in the wrong shade beats a diagram that will not
 * render.
 */
function skin(): string[] {
	return [
		'hide empty members',
		'skinparam shadowing false',
		'skinparam roundCorner 6',
		'skinparam packageStyle rectangle',
		`skinparam backgroundColor ${PALETTE.page}`,
		'skinparam defaultFontName "Inter, Segoe UI, Helvetica, Arial, sans-serif"',
		'skinparam defaultFontSize 13',
		`skinparam defaultFontColor ${PALETTE.ink}`,
		'',
		'skinparam package {',
		`\tBackgroundColor ${PALETTE.aggregateFill}`,
		`\tBorderColor ${PALETTE.aggregateBorder}`,
		'\tBorderThickness 1.5',
		'\tBorderStyle dashed',
		`\tFontColor ${PALETTE.aggregateTitle}`,
		'\tFontSize 15',
		'\tFontStyle bold',
		'}',
		'',
		'skinparam class {',
		`\tBackgroundColor ${PALETTE.valueFill}`,
		`\tBorderColor ${PALETTE.greyBorder}`,
		'\tBorderThickness 1.5',
		`\tFontColor ${PALETTE.ink}`,
		'\tFontSize 13',
		'\tFontStyle bold',
		`\tAttributeFontColor ${PALETTE.inkMuted}`,
		'\tAttributeFontSize 12',
		`\tStereotypeFontColor ${PALETTE.inkMuted}`,
		'\tStereotypeFontSize 10',
		'}',
		'',
		'skinparam enum {',
		`\tBackgroundColor ${PALETTE.enumFill}`,
		`\tBorderColor ${PALETTE.greyBorder}`,
		'\tBorderThickness 1.5',
		`\tFontColor ${PALETTE.ink}`,
		`\tAttributeFontColor ${PALETTE.inkMuted}`,
		'\tAttributeFontSize 12',
		'}',
		'',
		'skinparam note {',
		`\tBackgroundColor ${PALETTE.noteFill}`,
		`\tBorderColor ${PALETTE.noteBorder}`,
		`\tFontColor ${PALETTE.aggregateTitle}`,
		'\tFontSize 11',
		'}',
		'',
		`skinparam ArrowColor ${PALETTE.line}`,
		'skinparam ArrowThickness 1.4',
		`skinparam ArrowFontColor ${PALETTE.inkMuted}`,
		'skinparam ArrowFontSize 11',
	];
}

function membersOf(model: DomainModel, aggregate: AggregateNode): Member[] {
	// The aggregate's own order, so the file reads in the order it was written.
	const byId = new Map(model.members.map((member) => [member.id, member] as const));
	return aggregate.members
		.map((id) => byId.get(id))
		.filter((member): member is Member => member !== undefined);
}

/**
 * One declaration, with the rows the canvas shows in it.
 *
 * `rowsOf` is the canvas's, so the identity line, the attribute order and the
 * `name: type` spacing cannot drift from what the tool draws — the same
 * argument the SVG export makes by copying the live tree rather than redrawing
 * it.
 */
function declare(member: Member, alias: Map<Id, string>, indent: string): string[] {
	const name = alias.get(member.id) ?? safe(member.name);
	const keyword = member.kind === 'enum' ? 'enum' : 'class';
	const head = `${keyword} ${quoted(member.name)} as ${name} <<${plain(stereotypeOf(member))}>>${colour(member)}`;

	const rows = rowsOf(member);
	if (rows.length === 0) return [`${indent}${head}`];
	return [`${indent}${head} {`, ...rows.map((row) => `${indent}\t${row}`), `${indent}}`];
}

/** The box's fill and border, as `Diagram.tsx`'s `paint` chooses them. */
function colour(member: Member): string {
	if (member.kind === 'entity' && member.root) {
		return ` ${PALETTE.rootFill};line:${PALETTE.rootBorder};text:${PALETTE.rootTitle}`;
	}
	if (member.kind === 'entity') return ` ${PALETTE.entityFill};line:${PALETTE.entityBorder}`;
	if (member.kind === 'enum') return ` ${PALETTE.enumFill};line:${PALETTE.greyBorder}`;
	return ` ${PALETTE.valueFill};line:${PALETTE.greyBorder}`;
}

/**
 * The intent and the invariants, as a note on the root.
 *
 * On the root rather than on the package because PlantUML attaches a note to a
 * class and not to a package, and the root is the aggregate's face anyway — it
 * is the thing everything outside the boundary is allowed to name.
 */
function noteFor(aggregate: AggregateNode, alias: Map<Id, string>): string[] {
	const anchor = aggregate.root ? alias.get(aggregate.root) : undefined;
	if (!anchor) return [];

	const lines: string[] = [];
	if (aggregate.intent) lines.push(flatten(aggregate.intent));
	if (aggregate.invariants.length > 0) {
		if (lines.length > 0) lines.push('');
		lines.push('**Invariants**');
		lines.push(...aggregate.invariants.map((invariant) => `* ${flatten(invariant)}`));
	}
	if (lines.length === 0) return [];

	return [`note top of ${anchor}`, ...lines.map((line) => (line ? `\t${line}` : '')), 'end note'];
}

/**
 * Names are identities and are unique within a model, so an alias derived from
 * the name is unique too — except where two names differ only in punctuation
 * this strips. The counter covers that rather than trusting it not to happen.
 */
function aliases(model: DomainModel): Map<Id, string> {
	const taken = new Set<string>();
	const map = new Map<Id, string>();

	for (const member of model.members) {
		let name = safe(member.name);
		while (taken.has(name)) name = `${name}_`;
		taken.add(name);
		map.set(member.id, name);
	}

	// An aggregate answers to its root's alias.
	//
	// `references` names an aggregate — that is the rule the parser enforces —
	// and PlantUML relates classes rather than packages. The root is what an
	// aggregate exposes anyway: holding its id *is* referencing the aggregate,
	// so the arrow lands where the identity actually lives.
	for (const aggregate of model.aggregates) {
		const root = aggregate.root ? map.get(aggregate.root) : undefined;
		if (root) map.set(aggregate.id, root);
	}
	return map;
}

/** A PlantUML identifier: letters, digits and underscores, never leading digit. */
function safe(name: string): string {
	const cleaned = name.replace(/[^A-Za-z0-9_]/g, '');
	return /^[0-9]/.test(cleaned) || cleaned === '' ? `_${cleaned}` : cleaned;
}

/** A name PlantUML will take verbatim. The lexer forbids `"` inside one. */
function quoted(name: string): string {
	return `"${name}"`;
}

/** `«entity»` is the canvas's spelling; `<<entity>>` is PlantUML's. */
function plain(stereotype: string): string {
	return stereotype.replace(/[«»]/g, '').trim();
}

/**
 * Prose from the source, on one line.
 *
 * The `.ddm` wraps its long strings across lines with the indentation of the
 * file, and carrying that indentation into a note would put the wrapping of one
 * document inside another.
 */
function flatten(text: string): string {
	return text.replace(/\s+/g, ' ').trim();
}
